org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m
android.useAndroidX=true
android.nonFinalResIds=true
kotlin.code.style=official
android.enableJetifier=false
GOOGLE_WEB_CLIENT_ID=199063100402-qfpep80bf7ee52qclqlmoqi0fljq2i1v.apps.googleusercontent.com
